services:
  inference-server:
    image: roboflow/roboflow-inference-server-cpu:latest
    ports:
      - "9001:9001"
    environment:
      - ROBOFLOW_API_KEY=vsFE5RCISwR0yitbIbDO
    volumes:
      - inference_models:/tmp/cache   # les poids sont cachés ici
    restart: unless-stopped

volumes:
  inference_models:
