"use client";

/**
 * FacadeRapportDialog -- Report generation dialog for facade analysis.
 * Shows a preview of report sections, "Generate PDF" button (toast placeholder),
 * and "Copy summary" button.
 */

import { useState } from "react";
import {
  X,
  FileDown,
  Copy,
  Check,
  FileText,
  BarChart3,
  List,
  Ruler,
  ShieldCheck,
  Calculator,
} from "lucide-react";
import { FacadeAnalysisResult } from "@/lib/types";
import { useLang } from "@/lib/lang-context";
import { dt, DTKey } from "@/lib/i18n";
import { toast } from "@/components/ui/use-toast";

/* ---- Props ---- */
interface FacadeRapportDialogProps {
  result: FacadeAnalysisResult;
  onClose: () => void;
}

/* ---- Report sections ---- */
interface ReportSection {
  icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>;
  label: string;
  detail: string;
  color: string;
}

/* ---- Helpers ---- */
const fmtN = (v: number, d = 1) =>
  v.toLocaleString("fr-FR", { maximumFractionDigits: d });

function buildSummaryText(result: FacadeAnalysisResult, isFr: boolean): string {
  const fa = result.facade_area_m2;
  const oa = result.openings_area_m2;
  const solidArea = fa != null && oa != null ? Math.max(0, fa - oa) : null;
  const ratio = result.ratio_openings;

  const lines: string[] = [];
  lines.push(isFr ? "=== RAPPORT ANALYSE FACADE ===" : "=== FACADE ANALYSIS REPORT ===");
  lines.push(`Date: ${new Date().toLocaleDateString("fr-FR")}`);
  lines.push("");

  lines.push(isFr ? "-- KPIs --" : "-- KPIs --");
  if (fa != null) lines.push(`${isFr ? "Surface facade" : "Facade area"}: ${fmtN(fa)} m\u00B2`);
  if (oa != null) lines.push(`${isFr ? "Surface ouvertures" : "Openings area"}: ${fmtN(oa)} m\u00B2`);
  if (solidArea != null) lines.push(`${isFr ? "Surface murale nette" : "Net wall area"}: ${fmtN(solidArea)} m\u00B2`);
  if (ratio != null) lines.push(`${isFr ? "Ratio ouvertures" : "Opening ratio"}: ${(ratio * 100).toFixed(1)}%`);
  lines.push("");

  lines.push(isFr ? "-- Inventaire --" : "-- Inventory --");
  lines.push(`${isFr ? "Fenetres" : "Windows"}: ${result.windows_count}`);
  lines.push(`${isFr ? "Portes" : "Doors"}: ${result.doors_count}`);
  lines.push(`${isFr ? "Balcons" : "Balconies"}: ${result.balconies_count}`);
  lines.push(`${isFr ? "Niveaux" : "Floors"}: ${result.floors_count}`);
  lines.push(`${isFr ? "Elements totaux" : "Total elements"}: ${result.elements.length}`);
  lines.push("");

  if (solidArea != null) {
    lines.push(isFr ? "-- Estimations --" : "-- Estimates --");
    const paintL = solidArea * 0.35;
    lines.push(`${isFr ? "Peinture (2 couches)" : "Paint (2 coats)"}: ~${fmtN(paintL, 0)} L`);
    lines.push(`${isFr ? "ITE (12 cm)" : "ITE (12cm)"}: ~${fmtN(solidArea * 0.12, 1)} m\u00B3`);
  }

  lines.push("");
  lines.push(isFr ? "Genere par FloorScan" : "Generated by FloorScan");

  return lines.join("\n");
}

/* ---- Component ---- */
export default function FacadeRapportDialog({ result, onClose }: FacadeRapportDialogProps) {
  const { lang } = useLang();
  const d = (key: DTKey) => dt(key, lang);
  const isFr = lang === "fr";

  const [copied, setCopied] = useState(false);

  /* Report sections preview */
  const sections: ReportSection[] = [
    {
      icon: FileText,
      label: isFr ? "En-tete projet" : "Project header",
      detail: isFr
        ? "Nom du projet, adresse, date, reference"
        : "Project name, address, date, reference",
      color: "#64748b",
    },
    {
      icon: BarChart3,
      label: isFr ? "KPIs resume" : "KPI summary",
      detail: isFr
        ? "Surface facade, ouvertures, ratio vitrage, niveaux"
        : "Facade area, openings, glazing ratio, floors",
      color: "#f59e0b",
    },
    {
      icon: List,
      label: isFr ? "Inventaire des elements" : "Element inventory",
      detail: isFr
        ? `${result.windows_count} fenetres, ${result.doors_count} portes, ${result.balconies_count} balcons`
        : `${result.windows_count} windows, ${result.doors_count} doors, ${result.balconies_count} balconies`,
      color: "#60a5fa",
    },
    {
      icon: Ruler,
      label: isFr ? "Surfaces" : "Areas",
      detail: isFr
        ? "Facade totale, ouvertures, murale nette"
        : "Total facade, openings, net wall",
      color: "#34d399",
    },
    {
      icon: ShieldCheck,
      label: isFr ? "Conformite" : "Compliance",
      detail: isFr
        ? "Ratio vitrage RE2020, PMR, ITE"
        : "RE2020 glazing ratio, PMR, ITE",
      color: "#10b981",
    },
    {
      icon: Calculator,
      label: isFr ? "Estimations" : "Estimates",
      detail: isFr
        ? "Peinture, echafaudage, menuiseries, ITE"
        : "Paint, scaffolding, openings, ITE",
      color: "#a78bfa",
    },
  ];

  const handleGeneratePdf = () => {
    toast({
      title: isFr ? "Rapport genere" : "Report generated",
      description: isFr
        ? "La generation PDF facade sera disponible prochainement."
        : "Facade PDF generation will be available soon.",
      variant: "success",
    });
  };

  const handleCopySummary = async () => {
    try {
      const text = buildSummaryText(result, isFr);
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast({
        title: isFr ? "Resume copie" : "Summary copied",
        variant: "success",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: isFr ? "Erreur de copie" : "Copy error",
        variant: "error",
      });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Dialog */}
      <div className="relative glass rounded-2xl border border-white/10 w-full max-w-md p-6 space-y-5 shadow-2xl overflow-y-auto max-h-[90vh]">
        {/* Close */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Title */}
        <div>
          <h3 className="font-display text-lg font-semibold text-white flex items-center gap-2">
            <FileDown className="w-5 h-5 text-sky-400" />
            {isFr ? "Rapport d'analyse facade" : "Facade Analysis Report"}
          </h3>
          <p className="text-xs text-slate-500 mt-1">
            {isFr
              ? "Apercu des sections du rapport"
              : "Report sections preview"}
          </p>
        </div>

        {/* Sections preview */}
        <div className="space-y-2">
          {sections.map((sec, i) => {
            const Icon = sec.icon;
            return (
              <div
                key={i}
                className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/5"
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                  style={{ backgroundColor: sec.color + "20" }}
                >
                  <Icon className="w-4 h-4" style={{ color: sec.color }} />
                </div>
                <div className="min-w-0">
                  <div className="text-sm font-medium text-slate-200">
                    {sec.label}
                  </div>
                  <div className="text-xs text-slate-500 mt-0.5">
                    {sec.detail}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Action buttons */}
        <div className="space-y-2">
          <button
            onClick={handleGeneratePdf}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-sky-500 hover:bg-sky-600 text-white font-semibold text-sm transition-colors"
          >
            <FileDown className="w-4 h-4" />
            {isFr ? "Generer PDF" : "Generate PDF"}
          </button>

          <button
            onClick={handleCopySummary}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 font-medium text-sm transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-400">
                  {isFr ? "Copie !" : "Copied!"}
                </span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                {isFr ? "Copier le resume" : "Copy summary"}
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
